### ISSUE TITLE
Setup does not work with OpenSSL 1.1.0f

### ISSUE THREAD

**Issue by si87** [xLinkOut/ScreenCast-RPi#2]
Latest RPi standard installation on a RPi3 will fail during execution unfortunately.

```
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -I src/core -I src/event -I src/event/modules -I src/os/unix -I ../nginx-rtmp-module-master -I objs \
	-o objs/src/event/ngx_event_openssl.o \
	src/event/ngx_event_openssl.c
src/event/ngx_event_openssl.c: In function ‘ngx_ssl_connection_error’:
src/event/ngx_event_openssl.c:2026:21: error: ‘SSL_R_NO_CIPHERS_PASSED’ undeclared (first use in this function)
             || n == SSL_R_NO_CIPHERS_PASSED                          /*  182 */
                     ^~~~~~~~~~~~~~~~~~~~~~~
src/event/ngx_event_openssl.c:2026:21: note: each undeclared identifier is reported only once for each function it appears in
```
